services:
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: monitoring-local
    command:
      - monitoring
      - "--url=${BETTER_STACK_URL}"
      - "--interval=5"
      - "--cpu-limit=5"
      - "--memory-limit=10"
      - "--disk-limit=85"
    volumes:
      - /:/host:ro
    pid: host
    privileged: true
    restart: unless-stopped 